[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF8C00"
backgroundColor = "#FFF8DC"
secondaryBackgroundColor = "#FFEFD5"
textColor = "#8B4513"

[logger]
level = "info"